### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by m1ch490** [MarcusCalidus/excel-exporter#1]
Hi Marco,

a Label can be NULL but if a Value Field is NULL or 0 i get the following error.

`UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)`

**Comment by MarcusCalidus** [comment]
Exception handling is now in place. The actual exception is written to the log. Also files can be optionally filtered by pattern.
